Name:           ros-indigo-turtlebot-arm
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS turtlebot_arm package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/turtlebot_arm
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-turtlebot-arm-bringup
Requires:       ros-indigo-turtlebot-arm-description
Requires:       ros-indigo-turtlebot-arm-ikfast-plugin
Requires:       ros-indigo-turtlebot-arm-kinect-calibration
Requires:       ros-indigo-turtlebot-arm-moveit-config
Requires:       ros-indigo-turtlebot-arm-moveit-demos
BuildRequires:  ros-indigo-catkin

%description
The turtlebot arm meta package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Aug 30 2014 Jorge Santos <jsantossimon@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

* Fri Aug 22 2014 Jorge Santos <jsantossimon@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

